# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Linting

on: [push]

jobs:

  check-style:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: 1.24
    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: 20
    - name: Check N-Quads are sorted
      run: |
        set -e
        for f in $(find . -name "*.nq"); do
          echo "Checking file $f"
          LC_ALL=C sort "$f" | diff -u "$f" -
        done

    # Step 3: Run Prettier Check via npx
    - name: Prettier Lint (check formatting)
      run: npx prettier --check "**/*.{html,js,json,md}"

    - name: Check existing migrations are not altered
      run: | 
        git diff --name-status origin/main...HEAD migrations/ \
        | grep -E '^[MD]' \
        | grep -v '^migrations/migrations.go' \
        | grep -v '^migrations/migration_test.go' \
        && echo "‚ùå Existing migration modified or deleted" && exit 1 || true

  check-nil:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.24
      - name: Nilaway
        run: |
          go install go.uber.org/nilaway/cmd/nilaway@latest
          nilaway ./...

